openapi: "3.0.1"
info:
  title: "Greeting Api"
  description: "Greeting API for Riyaz Sayyad Tutorial (Udemy)"
  version: "1.0"
servers:
- url: "https://7apx5c3x79.execute-api.eu-north-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/Prod"
paths:
  /greet/{name}:
    get:
      description: "Greeting with several languages"
      parameters:
      - name: "name"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "lang"
        in: "query"
        required: true
        schema:
          type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/empty"
        required: true
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content: {}
      x-amazon-apigateway-request-validator: "params-only"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GreetMeFunction.Arn}/invocations"
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
    options:
      parameters:
      - name: "name"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "{}\n"
        requestTemplates:
          application/json: "{\n  \"statusCode\" : 200\n}\n"
        passthroughBehavior: "when_no_match"
        type: "mock"
  /math/{operation}:
    post:
      description: "Allows add, subtract, multiply, delete two numbers "
      parameters:
      - name: "operation"
        in: "path"
        required: true
        schema:
          type: "string"
      requestBody:
        description: "Input for Calculator Endpoint"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/mathinput"
        required: true
      responses:
        "400":
          description: "400 response"
          content: {}
        "500":
          description: "500 response"
          content: {}
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content: {}
      x-amazon-apigateway-request-validator: "body-only"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CalculatorFunction.Arn}/invocations"
        responses:
          ".*Unsupported.*":
            statusCode: "400"
            responseTemplates:
              application/json: "{\n    \"errorMessage\":\"$input.path('$.errorMessage')\"\
                \n}"
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "{\n    \"result\": $input.path('$.body')\n}"
          ".*Error.*":
            statusCode: "500"
        requestTemplates:
          application/json: "#set($inputRoot = $input.path('$'))\n{\n  \"input\" :\
            \ {\n    \"operand1\" : $inputRoot.num1,\n    \"operand2\" : $inputRoot.num2\n\
            \  },\n  \"operation\" : \"$input.params('operation')\"\n}"
        passthroughBehavior: "when_no_templates"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    options:
      parameters:
      - name: "operation"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,POST'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "{}\n"
        requestTemplates:
          application/json: "{\n  \"statusCode\" : 200\n}\n"
        passthroughBehavior: "when_no_match"
        type: "mock"
components:
  schemas:
    mathinput:
      title: "Math Input"
      required:
      - "num1"
      - "num2"
      type: "object"
      properties:
        num1:
          type: "number"
        num2:
          type: "number"
      description: "Input for Calculator Endpoint"
    empty:
      type: "object"
      properties:
        empty:
          type: "string"
    CalcInput:
      title: "Calculator Function Input"
      description: "Input for Calculator Lambda Function"
      type: object
      required:
        - "operation"
        - "input"
      properties:
        operation:
          type: string
        input:
          type: object
          required:
            - "operand1"
            - "operand2"
          properties:
            operand1:
              type: number
            operand2:
              type: number
x-amazon-apigateway-documentation:
  version: "1.0"
  createdDate: "2022-01-10T20:01:37Z"
  documentationParts:
    - location:
        type: "API"
      properties:
        info:
          description: "Greeting API for Riyaz Sayyad Tutorial (Udemy)"
    - location:
        type: "METHOD"
        path: "/greet/{name}"
        method: "GET"
      properties:
        description: "Greeting with several languages"
    - location:
        type: "METHOD"
        path: "/math/{operation}"
        method: "POST"
      properties:
        description: "Allows add, subtract, multiply, delete two numbers "
    - location:
        type: "MODEL"
        name: "CalcInput"
      properties:
        title: "Calculator Function Input"
        description: "Input for Calculator Lambda Function"
    - location:
        type: "MODEL"
        name: "mathinput"
      properties:
        title: "Math Input"
        description: "Input for Calculator Endpoint"
    - location:
        type: "REQUEST_BODY"
        path: "/math/{operation}"
        method: "POST"
      properties:
        description: "Input for Calculator Endpoint"
    - location:
        type: "RESPONSE"
        path: "/greet/{name}"
        method: "GET"
        statusCode: "200"
      properties:
        description: "200 response"
    - location:
        type: "RESPONSE"
        path: "/greet/{name}"
        method: "OPTIONS"
        statusCode: "200"
      properties:
        description: "200 response"
    - location:
        type: "RESPONSE"
        path: "/math/{operation}"
        method: "OPTIONS"
        statusCode: "200"
      properties:
        description: "200 response"
    - location:
        type: "RESPONSE"
        path: "/math/{operation}"
        method: "POST"
        statusCode: "200"
      properties:
        description: "200 response"
    - location:
        type: "RESPONSE"
        path: "/math/{operation}"
        method: "POST"
        statusCode: "400"
      properties:
        description: "400 response"
    - location:
        type: "RESPONSE"
        path: "/math/{operation}"
        method: "POST"
        statusCode: "500"
      properties:
        description: "500 response"
x-amazon-apigateway-request-validators:
  params-only:
    validateRequestParameters: true
    validateRequestBody: false
  body-only:
    validateRequestParameters: false
    validateRequestBody: true
