AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  greet-me

  Sample SAM Template for greet-me
  
Globals:
  Function:
    Timeout: 3

Resources:
  GreetMeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: greetMe/
      Handler: index.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        GreetByName:
          Type: Api
          Properties:
            Path: /greet/{name}
            Method: get
            RestApiId: !Ref GreetingApi
            RequestParameters:
              - method.request.querystring.lang:
                  Required: true
                  Caching: false

  GreetingApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Greeting Api
      Description: Greeting API for Riyaz Sayyad Tutorial (Udemy)
      StageName: Prod


Outputs:
  GreetMeItalian:
    Description: "API Gateway endpoint URL for Greeting me in Italian"
    Value: !Sub "https://${GreetingApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/greet/Art?lang=it"
  GreetKateFrance:
    Description: "API Gateway endpoint URL for Greeting Kate in French"
    Value: !Sub "https://${GreetingApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/greet/Kate?lang=fr"
  GreetArinaDefault:
    Description: "API Gateway endpoint URL for Greeting Arina"
    Value: !Sub "https://${GreetingApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/greet/Arina"
