AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  greet-me

  Sample SAM Template for greet-me
  
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs14.x
    Architectures:
      - x86_64

Resources:
  GreetMeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: greetMe/
      Handler: index.handler
      Events:
        GreetByName:
          Type: Api
          Properties:
            Path: /greet/{name}
            Method: get
            RestApiId: !Ref GreetingApi

  CalculatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: calc/
      Handler: calculator.handler
      Events:
        Math:
          Type: Api
          Properties:
            Path: /math/{operation}
            Method: post
            RestApiId: !Ref GreetingApi

  GreetingApi:
    Type: AWS::Serverless::Api
    DependsOn: ApiCWLRoleArn
    Properties:
      Name: Greeting Api
      Description: Greeting API for Riyaz Sayyad Tutorial (Udemy)
      StageName: Prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: Greeting Api-Prod-oas30-apigateway.yaml
      MethodSettings:
        - LoggingLevel: INFO # Enable CloudWatch Logs
          ResourcePath: '/*' # allows for logging on any resource
          HttpMethod: '*' # allows for logging on any method
        - DataTraceEnabled: false # Log full requests/responses data
          ResourcePath: '/*'
          HttpMethod: '*'
        - MetricsEnabled: false # Enable Detailed CloudWatch Metrics
          ResourcePath: '/*'
          HttpMethod: '*'

  ApiCWLRoleArn:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt CloudWatchRole.Arn

  # IAM Role for API GW + CWL
  CloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Action: 'sts:AssumeRole'
          Effect: Allow
          Principal:
            Service: apigateway.amazonaws.com
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs'

Outputs:
  GreetMeItalian:
    Description: "API Gateway endpoint URL for Greeting me in Italian"
    Value: !Sub "https://${GreetingApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/greet/Art?lang=it"
  GreetKateFrance:
    Description: "API Gateway endpoint URL for Greeting Kate in French"
    Value: !Sub "https://${GreetingApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/greet/Kate?lang=fr"
  GreetArinaDefault:
    Description: "API Gateway endpoint URL for Greeting Arina"
    Value: !Sub "https://${GreetingApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/greet/Arina"
