AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  greet-me

  Sample SAM Template for greet-me
  
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs14.x
    Architectures:
      - x86_64

Resources:
  GreetMeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: greetMe/
      Handler: index.handler
      Events:
        GreetByName:
          Type: Api
          Properties:
            Path: /greet/{name}
            Method: get
            RestApiId: !Ref GreetingApi
            RequestModel:
              Model: Empty
              Required: false
              ValidateBody: false
              ValidateParameters: true
            RequestParameters:
              - method.request.querystring.lang:
                  Required: true
                  Caching: false

  CalculatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: calc/
      Handler: calculator.handler
      Events:
        Math:
          Type: Api
          Properties:
            Path: /math/{operation}
            Method: post
            RestApiId: !Ref GreetingApi
            RequestModel:
              Model: MathInput
              Required: true
              ValidateBody: true

  GreetingApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Greeting Api
      Description: Greeting API for Riyaz Sayyad Tutorial (Udemy)
      StageName: Prod
#      DefinitionBody:
#        Fn::Transform:
#          Name: AWS::Include
#          Parameters:
#            Location: Greeting Api-Prod-oas30-apigateway.yaml
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'GET,POST'"
      Models:
        Empty:
          type: object
          properties:
            empty:
              type: string
        CalcInput:
          type: object
          required:
            - operation
            - input
          properties:
            operation:
              type: string
            input:
              type: object
              required:
                - operand1
                - operand2
              properties:
                operand1:
                  type: number
                operand2:
                  type: number
        MathInput:
          type: object
          required:
            - operand1
            - operand2
          properties:
            operand1:
              type: number
            operand2:
              type: number

Outputs:
  GreetMeItalian:
    Description: "API Gateway endpoint URL for Greeting me in Italian"
    Value: !Sub "https://${GreetingApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/greet/Art?lang=it"
  GreetKateFrance:
    Description: "API Gateway endpoint URL for Greeting Kate in French"
    Value: !Sub "https://${GreetingApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/greet/Kate?lang=fr"
  GreetArinaDefault:
    Description: "API Gateway endpoint URL for Greeting Arina"
    Value: !Sub "https://${GreetingApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/greet/Arina"
