version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "image-processing-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1alt62pqr870u"
s3_prefix = "image-processing-app"
region = "eu-north-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "AppBucketName=\"art-image-processing\" ImageMagickLayer=\"arn:aws:lambda:eu-north-1:392971033516:layer:image-magick:1\""
