AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  image-processing-app

  SAM Template for image-processing-app

Parameters:
  AppBucketName:
    Type: String
    Description: "REQUIRED: Unique S3 bucket name to use for the app."
  ImageMagickLayer:
    Type: String
    Description: "REQUIRED: ARN of Manually deployed ImageMagick Lambda Layer"

Globals:
  Function:
    Runtime: nodejs14.x
    Architectures:
      - x86_64
    MemorySize: 128

Resources:

  ImageProcessingStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      Type: EXPRESS
      DefinitionUri: statemachine/state_machine.asl.json
      DefinitionSubstitutions:
        GetFileTypeFunctionArn: !GetAtt GetFileTypeFunction.Arn
        CopyFileFunctionArn: !GetAtt CopyFileFunction.Arn
        CreateCopyParametersFunctionArn: !GetAtt CreateCopyParametersFunction.Arn
        ResizeImageFunctionArn: !GetAtt ResizeImageFunction.Arn
        WriteToDynamoDbFunctionArn: !GetAtt WriteToDynamoDbFunction.Arn
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref GetFileTypeFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref CopyFileFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref CreateCopyParametersFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ResizeImageFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref WriteToDynamoDbFunction
        - S3CrudPolicy:
            BucketName: !Ref AppBucketName

  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AppBucketName

  ImageProcessingTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Type: String
        Name: id
      ProvisionedThroughput:
        WriteCapacityUnits: 3
        ReadCapacityUnits: 3

  InvokeImageProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/s3-observer/
      Handler: invoke-image-processor.handler
      Timeout: 60
      Environment:
        Variables:
          STATE_MACHINE_ARN: !GetAtt ImageProcessingStateMachine.Arn
      Policies:
        - StepFunctionsExecutionPolicy:
            StateMachineName: !GetAtt ImageProcessingStateMachine.Name
      Events:
        S3NewObjectEvent:
          Type: S3
          Properties:
            Bucket: !Ref AppBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: "original/"

  GetFileTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/processing/
      Handler: get-file-type.handler

  CopyFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/processing/
      Handler: copy-file.handler
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref AppBucketName

  CreateCopyParametersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/processing/
      Handler: create-copy-parameters.handler
      Environment:
        Variables:
          DESTINATION_FOLDER: dest2

  ResizeImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/processing/
      Handler: resize-image.handler
      Timeout: 60
      Layers:
        - !Ref ImageMagickLayer
      Environment:
        Variables:
          IMAGE_WIDTH_PX: 128
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref AppBucketName

  WriteToDynamoDbFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/processing/
      Handler: write-to-dynamo-db.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref ImageProcessingTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ImageProcessingTable

Outputs:
  ImageProcessingStateMachineArn:
    Description: "Image Processing state machine ARN"
    Value: !Ref ImageProcessingStateMachine

