AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  control-access-lambda-authorizer

  Sample SAM Template for control-access-lambda-authorizer
  
Globals:
  Function:
    Timeout: 3

Resources:

  ControlAccessApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Control Access Api
      Description: Control Access API for Riyaz Sayyad Tutorial (Udemy)
      StageName: Prod
      Auth:
        DefaultAuthorizer: LambdaAuthorizer
        Authorizers:
          LambdaAuthorizer:
            FunctionPayloadType: TOKEN
            FunctionArn: !GetAtt AuthorizerFunction.Arn
            Identity:
              ReauthorizeEvery: 300
              Headers:
                - Authorization

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref ControlAccessApi

  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: lambda-auth.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64


Outputs:
  ControlAccessApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ControlAccessApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
