AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  control-access-cognito-authorizer

  Sample SAM Template for control-access-cognito-authorizer

Parameters:
  MyUserPoolArn:
    Type: String
    Default: arn:aws:cognito-idp:eu-north-1:392971033516:userpool/eu-north-1_6584Kr6zk

Globals:
  Function:
    Timeout: 3

Resources:

  ControlAccessApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Control Access Api
      Description: Control Access API for Riyaz Sayyad Tutorial (Udemy)
      StageName: Prod
      Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !Ref MyUserPoolArn
            Identity:
              ReauthorizeEvery: 300
              Headers:
                - Authorization

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref ControlAccessApi

Outputs:
  ControlAccessApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ControlAccessApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
