### Create new User
POST {{serverUrl}}/users
Accept: application/json
Content-Type: application/json

{
  "firstName": "Art",
  "lastName": "Shyshkin",
  "email": "art.shyshkin@mailinator.com",
  "website": "example.shyshkin.net"
}

### Get User
GET {{serverUrl}}/users/8c8a5df6-561b-4926-a293-565048cb8b12
Accept: application/json



