###  Serverless API Gateway math add operation LAMBDA-PROXY Integration
POST {{serverUrl}}/math/add
Content-Type: application/json

{
  "number1": 13,
  "number2": 5
}

###  Serverless API Gateway math add operation LAMBDA Integration
POST {{serverUrl}}/math/addBodyMapping
Content-Type: application/json

{
  "input": {
    "operand1": 13,
    "operand2": 5
  }
}
