service: hello-serverless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  profile: serverless-admin
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-north-1

functions:
  hello:
    handler: handler.hello
