service: hello-serverless

frameworkVersion: '2'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  profile: serverless-admin
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-north-1
  memorySize: 128
  timeout: 3

functions:
  hello:
    handler: handler.hello
    vpc:
      securityGroupIds:
        - sg-24aebf45
      subnetIds:
        - subnet-ade616e0
        - subnet-5d30e626
  addFunction:
    handler: add.handler
    events:
      - http:
          path: math/add
          method: post
          cors: true

  addBodyMapping:
    handler: add-body-mapping.handler
    events:
      - http:
          path: math/addBodyMapping
          method: post
          cors: true
          integration: lambda
          request:
            template:
              application/json: >
                #set($inputRoot = $input.path('$'))
                {
                  "number1": $inputRoot.input.operand1,
                  "number2": $inputRoot.input.operand2
                }
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
              Content-Type: "'application/json'"
            template: >
              #set($inputRoot = $input.path('$'))
              {
                "result": $inputRoot
              }

