###  Greet Art in Italian
GET {{serverUrl}}/greet/Art?lang=it&age=38
Accept: application/json
x-api-key: {{apiKey}}

###  Greet Art in Italian WITHOUT API Key -> Forbidden
GET {{serverUrl}}/greet/Art?lang=it&age=38
Accept: application/json

###  Greet Kate in French
GET {{serverUrl}}/greet/Kate?lang=fr
Accept: application/json
x-api-key: {{apiKey}}

###  Greet Arina without [lang] - 400 Bad Request
GET {{serverUrl}}/greet/Arina
Accept: application/json
x-api-key: {{apiKey}}

###  Greet Nazar in non-existing language
GET {{serverUrl}}/greet/Nazar?lang=oo
Accept: application/json
x-api-key: {{apiKey}}

###  Preflight request test
OPTIONS {{serverUrl}}/greet/Nazar
Accept: application/json

###  Preflight request test
OPTIONS {{serverUrl}}/math/add
Accept: application/json

###  Calculation - add
POST {{serverUrl}}/math/add
Accept: application/json
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "num1": 5,
  "num2": 3
}

###  Calculation - FORBIDDEN
POST {{serverUrl}}/math/add
Accept: application/json
Content-Type: application/json

{
  "num1": 5,
  "num2": 3
}

###  Calculation - subtract
POST {{serverUrl}}/math/subtract
Accept: application/json
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "num1": 5,
  "num2": 3
}

###  Calculation - multiply
POST {{serverUrl}}/math/multiply
Accept: application/json
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "num1": 5,
  "num2": 3
}

###  Calculation - divide
POST {{serverUrl}}/math/divide
Accept: application/json
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "num1": 48,
  "num2": 3
}

###  Calculation - unsupported
POST {{serverUrl}}/math/foo
Accept: application/json
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "num1": 48,
  "num2": 3
}


