version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "control-access-cognito-authorizer-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1alt62pqr870u"
s3_prefix = "control-access-cognito-authorizer-sam"
region = "eu-north-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CognitoUserPoolName=\"ArtRiyazUserPool\" CognitoUserPoolClientName=\"ArtRiyazUserPoolClient\""
image_repositories = []
