AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  control-access-cognito-authorizer

  Sample SAM Template for control-access-cognito-authorizer

Parameters:
  CognitoUserPoolName:
    Type: String
    Default: ArtRiyazUserPool
  CognitoUserPoolClientName:
    Type: String
    Default: ArtRiyazUserPoolClient

Globals:
  Function:
    Timeout: 3

Resources:

  ControlAccessApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Control Access Api
      Description: Control Access API for Riyaz Sayyad Tutorial (Udemy)
      StageName: Prod
      Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !GetAtt MyCognitoUserPool.Arn
            Identity:
              ReauthorizeEvery: 300
              Headers:
                - Authorization

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref ControlAccessApi

  MyCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref CognitoUserPoolName
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
#      UsernameAttributes:
#        - email
#      Schema:
#        - AttributeDataType: String
#          Name: email
#          Required: false

  MyCognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref MyCognitoUserPool
      ClientName: !Ref CognitoUserPoolClientName
      GenerateSecret: false
      PreventUserExistenceErrors: ENABLED
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

Outputs:
  ControlAccessApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ControlAccessApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
