AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  apigw-step-functions

  Sample SAM Template for apigw-step-functions

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs14.x
    Architectures:
      - x86_64
    CodeUri: functions/calculator/

Resources:

  HelloWorldStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/state_machine.asl.json
      DefinitionSubstitutions:
        CalculateSquareFunctionArn: !GetAtt CalculateSquareFunction.Arn
      Policies:  # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref CalculateSquareFunction
      Events:
        MathApiCall:
          Type: Api
          Properties:
            Method: post
            Path: /math

  CalculateSquareFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: calculateSquare.lambdaHandler
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !GetAtt CalculatorFunction.Arn
      Environment:
        Variables:
          CALCULATOR_FUNCTION_NAME: !Ref CalculatorFunction

  CalculatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: calculator.handler

Outputs:
  HelloWorldStateMachineArn:
    Description: "Hello World state machine ARN"
    Value: !Ref HelloWorldStateMachine

  MathApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/math"

