version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "node-resize-image-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1alt62pqr870u"
s3_prefix = "node-resize-image-stack"
region = "eu-north-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppBucketName=\"art-node-resize-image\""
image_repositories = []
